# fly.toml app configuration file generated for ai-archetype-quiz on 2025-06-25T23:12:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-archetype-quiz'
primary_region = 'ord'

[build]

[env]
  PORT = '8000'

[[mounts]]
  source = 'quiz_data'
  destination = '/app/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
